### ISSUE TITLE
Automatically register features on first usage

### ISSUE THREAD

**Issue by Zethson** [laminlabs/cellxgene-lamin-validator#12]
![image](https://github.com/laminlabs/cellxgene-lamin-validator/assets/21954664/15f2c6b8-4f75-4a1d-a73d-97b6a649e100)

IMO we can automate this by checking whether the `ln.Feature.lookup().dict()` is empty and then registering if necessary. A warning that this is happening should be sufficient.

**Comment by sunnyosun** [comment]
Achieved within the lamin-validator!
