### ISSUE TITLE
Make sure `.to_cellxgene` checks all requirements in CxG schema 5.0.0

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/cellxgene-lamin-validator#16]
https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.0.0/schema.md

**Comment by Zethson** [comment]
'schema_reference': 'https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md', 'schema_version': '4.0.0',

is how the schema information is stored in `uns`

**Comment by sunnyosun** [comment]
Got it! Then we can easily add it within the `.to_cellxgene()` function

**Comment by Zethson** [comment]
We settled on not checking all requirements. Only the most important ones and not while validating but only when `to_cellxgene`
